dbt_variant_utils:
    target: slimci
    outputs:
        slimci:
            type: snowflake
            account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
            user: "{{ env_var('SNOWFLAKE_USER') }}"
            password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
            role: "{{ env_var('SNOWFLAKE_ROLE') }}"
            warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE') }}"
            database: "{{ env_var('SNOWFLAKE_DATABASE') }}_ci"
            schema: "dbt_variant_utils"
            threads: "{{ env_var('SNOWFLAKE_THREADS') | as_number }}"
